java_library(
  name = 'module-all',
  srcs = glob(['**/*.java']),
  visibility = ['PUBLIC'],
  deps = [
    '//montezuma-common:module-all'
  ] +
  [
    '//lib:aspectjrt',
    '//lib:commons-cli',
  ],
)

project_config(
  src_target = ':module-all',
)
