java_library(
  name = 'module-all',
  srcs = glob(['**/*.java']),
  visibility = ['PUBLIC'],
  deps = [
    '//montezuma-recording:module-all',
    '//montezuma-replaying:module-all',
    '//montezuma-test-generation:module-all',
  ],
)

project_config(
  src_target = ':module-all',
)
